---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      customize:
        memory: 512
        cpuexecutioncap: 50

suites:
  - name: controller
    run_list:
      - recipe[openstack::controller]
    attributes:
